name: Python

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@c822b3bceb49cc612560c35bd3b731b6c826ef53

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E1,E2,E3,E4,E7,E9,W1,W2,W3,W4,W5,F63,F7,F82 --show-source --statistics
