# 任意のレジストリに Docker image を公開orビルドする。
# プルリクの作成・更新時に動作する。

name: Docker

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/docker.yml
  pull_request_target:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.merged == true && 'master' || github.event.pull_request.head.sha }}

jobs:
  docker-ci:
    name: Docker CI
    runs-on: ubuntu-latest

    steps:
      - name: Run book000/templates/workflows/reusables/docker.yml
        uses: book000/templates/workflows/reusables/docker.yml@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          targets: >-
            [
              { imageName: "tomacheese/twitter-dm-memo", context: ".", file: "Dockerfile", packageName: "twitter-dm-memo" }
            ]
